[package]
name = "flash-tools"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "flash_tools"
path = "src/lib.rs"

[dependencies]
flash-core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[lints]
workspace = true
