[package]
name = "flash-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "flash_tui"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1"
crossterm = "0.29"
flash-core = { path = "../core" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }

[lints]
workspace = true
